Moving to typescript pt 1
DonArtisan/technify-react pull request #22
Opened 2023-02-28 21:37 UTC by mariabug

2023-02-28 21:37 UTC, mariabug commented
Current dependencies on/for this PR:
* develop
  * **PR #20** <a href="https://app.graphite.dev/github/pr/DonArtisan/technify-react/20" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #21** <a href="https://app.graphite.dev/github/pr/DonArtisan/technify-react/21" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #22** <a href="https://app.graphite.dev/github/pr/DonArtisan/technify-react/22" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
        * **PR #23** <a href="https://app.graphite.dev/github/pr/DonArtisan/technify-react/23" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #24** <a href="https://app.graphite.dev/github/pr/DonArtisan/technify-react/24" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #25** <a href="https://app.graphite.dev/github/pr/DonArtisan/technify-react/25" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/DonArtisan/technify-react/22?utm_source=stack-comment).

2023-03-15 16:32 UTC, AguilarKevin commented on src/components/ProductCard.tsx
> +  product: Product
podes usar el helper `Pick` para que evites hacer la asercion `product as Product`

2023-03-15 16:38 UTC, AguilarKevin requested changes

2023-03-15 16:38 UTC, AguilarKevin commented on src/pages/home/index.tsx
>  import CategoriesList from '../../components/CategoriesList'
podes agregar un path alias para evitar poner todo el `../../../`

2023-03-15 16:38 UTC, AguilarKevin commented on src/pages/home/index.tsx
> +            <ProductCard key={index} product={product as Product} />
usar el index del item en el array es un anti-pattern porque el `key` prop debe ser unicom, podrias usar el id del `product`

2023-03-25 16:40 UTC, merged